#  sign up

post http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "nutlovekoon@gmail.com",
    "password" : "7777"
}

### sign in 

post http://localhost:3000/user/signin
Content-Type: application/json

{
    "email": "nutlovekoon@gmail.com",
    "password" : "7777"
}


### Find by email
post http://localhost:3000/user/findemail
Content-Type: application/json

{
     "email": "nutlovekoon@gmail.com"
}

### Find all user
get http://localhost:3000/user/alluser


### Clear everythingin database

DELETE http://localhost:3000/user/clear